name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Copy env
        run: cd packages/contracts && cp env/.env.sample env/.env

      - name: Check formatting
        run: cd packages/contracts && yarn run formatting:check

      - name: Compile
        run: cd packages/contracts && yarn run build

      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
        run: cd packages/contracts && yarn run test
